---
title: "3제강 합금철 대시보드"
output: 
    flexdashboard::flex_dashboard:
    orientation: rows
runtime: shiny
---
    
```{r setup, include=FALSE}
library(flexdashboard)
library(shinymanager)
# library(DBI)
# library(RMySQL)
library(dplyr)
library(DT)
# define some credentials (you can also use sqlite database)
credentials <- data.frame(
  user = c("shiny", "shinymanager"),
  password = c("azerty", "12345"),
  admin = c(FALSE, TRUE),
  stringsAsFactors = FALSE
)
auth <- callModule(
    module = auth_server,
    id = "auth",
    check_credentials = check_credentials(credentials)) # data.frame
    # check_credentials = check_credentials("path/to/credentials.sqlite", passphrase = "supersecret") # sqlite
```

```{r global, include=TRUE}
auth_ui(id = "auth")

```

Column {.sidebar}
-----------------------------------------------------------------------

Waiting time between eruptions and the duration of the eruption for the
Old Faithful geyser in Yellowstone National Park, Wyoming, USA.

```{r}
selectInput("n_breaks", label = "Number of bins:",
            choices = c(10, 20, 35, 50), selected = 20)

sliderInput("bw_adjust", label = "Bandwidth adjustment:",
            min = 0.2, max = 2, value = 1, step = 0.2)
```

Column
-----------------------------------------------------------------------

### Geyser Eruption Duration

```{r}

renderPlot({
          hist(faithful$eruptions, probability = TRUE, breaks = as.numeric(input$n_breaks),
               xlab = "Duration (minutes)", main = "Geyser Eruption Duration")
          dens <- density(faithful$eruptions, adjust = input$bw_adjust)
          lines(dens, col = "blue")
          })
```